region      = "ap-south-1"
prefix      = "dsuren-iac-lab"
prefix-lb   = "dsuren-iac-lab-lb"
prefix-tg   = "dsuren-iac-lab-tg"
vpc_cidr    = "192.168.1.0/25"
subnet_cidr = "192.168.1.0/24"
db_username = "dsurendran"
db_name     = "pgdb"
